# Site settings
title: tobiha.de
name: Tobias Hagemann
email: info [at] tobiha [dot] de
description: Tobias Hagemann • Developer & Designer • Based in Bonn, Germany
baseurl: ""
url: "https://tobiha.de"
mastodon_username: tobihagemann
twitter_username: tobihagemann
github_username: tobihagemann
youtube_username: tobihagemann
keybase_username: tobihagemann

# Plugins
plugins:
  - jekyll-paginate
  - jemoji

# Outputting
permalink: /:year/:month/:day/:title/

# Pagination
paginate: 10
paginate_path: /blog/page/:num/

# Sass/SCSS
sass:
  style: compressed
